<Project>
  <PropertyGroup>
    <Version>2.5.1</Version>
    <FileVersion>2.5.1.0</FileVersion>
    <AssemblyVersion>2.5.1.0</AssemblyVersion>
    <InformationalVersion>2.5.1+20260804.230000</InformationalVersion>
    <DefaultItemExcludes>$(DefaultItemExcludes);artifacts\**;.versioning\**</DefaultItemExcludes>
  </PropertyGroup>
</Project>
