<Project>
  <PropertyGroup>
    <Version>2.5.0</Version>
    <FileVersion>2.5.0.0</FileVersion>
    <AssemblyVersion>2.5.0.0</AssemblyVersion>
    <InformationalVersion>2.5.0+20260728.160000</InformationalVersion>
    <DefaultItemExcludes>$(DefaultItemExcludes);artifacts\**;.versioning\**</DefaultItemExcludes>
  </PropertyGroup>
</Project>
