<Project>
  <PropertyGroup>
    <Version>2.8.0</Version>
    <FileVersion>2.8.0.0</FileVersion>
    <AssemblyVersion>2.8.0.0</AssemblyVersion>
    <InformationalVersion>2.8.0+20260814.103303</InformationalVersion>
    <DefaultItemExcludes>$(DefaultItemExcludes);artifacts\**;.versioning\**</DefaultItemExcludes>
  </PropertyGroup>
</Project>
