using System.IO;
using System.Text.Json;
using MarqueeManager.Compositions.Core.Policy;
using MarqueeManager.Compositions.Core.Presentation;
using MarqueeManager.Compositions.Core.Resolution;

namespace MarqueeManager.Setup.Data;

/// <summary>
/// Reader/writer of state\media-presentation.json (schema
/// marqueemanager.media-presentation.v1). Ownership-guarded like every Setup JSON:
/// a file not generated by the Setup is never overwritten. Parsing/serialization
/// live in the shared domain; this only does the file I/O.
/// </summary>
public sealed class MediaPresentationStore
{
    private readonly string _pluginRoot;

    public MediaPresentationStore(string pluginRoot) => _pluginRoot = pluginRoot;

    public string DocumentPath => Path.Combine(_pluginRoot, "state", "media-presentation.json");

    public bool Exists => File.Exists(DocumentPath);

    public MediaPresentationDocument Load()
    {
        try
        {
            if (Exists)
                return MediaPresentationSerializer.TryParse(File.ReadAllText(DocumentPath)) ?? MediaPresentationDocument.Empty;
        }
        catch
        {
            // unreadable: behave as if empty (pure defaults)
        }
        return MediaPresentationDocument.Empty;
    }

    public bool IsOwnedBySetup()
    {
        if (!Exists) return true;
        try
        {
            using var doc = JsonDocument.Parse(File.ReadAllText(DocumentPath));
            return doc.RootElement.TryGetProperty("generatedBy", out var by)
                   && by.GetString() == MediaPresentationDocument.Generator;
        }
        catch
        {
            return false;
        }
    }

    public void Save(MediaPresentationDocument document)
    {
        if (Exists && !IsOwnedBySetup()) return; // never clobber a foreign document
        Directory.CreateDirectory(Path.GetDirectoryName(DocumentPath)!);
        if (Exists)
        {
            try { File.Copy(DocumentPath, DocumentPath + ".bak", overwrite: true); }
            catch { /* best-effort backup */ }
        }
        File.WriteAllText(DocumentPath, MediaPresentationSerializer.Serialize(document));
    }
}

/// <summary>
/// Immutable edits of a media-presentation document for the "use this source"
/// overrides. A checkbox stores an <c>enabled</c> delta on the matching target
/// (system- or game-scoped); "reset to surface" drops the whole target entry.
/// </summary>
public static class MediaPresentationEdits
{
    public static MediaPresentationDocument SetSourceEnabled(
        MediaPresentationDocument document, ResolutionContext context, SourceKind kind, bool enabled)
    {
        var targets = document.TargetPolicies.ToList();
        var index = targets.FindIndex(t => SameTarget(t, context));
        if (index >= 0)
        {
            var target = targets[index];
            var sources = target.Delta.Sources is { } existing
                ? new Dictionary<SourceKind, SourceSettingsDelta>(existing)
                : new Dictionary<SourceKind, SourceSettingsDelta>();
            var source = sources.TryGetValue(kind, out var sd) ? sd : new SourceSettingsDelta();
            sources[kind] = source with { Enabled = enabled };
            targets[index] = target with { Delta = target.Delta with { Sources = sources } };
        }
        else
        {
            var sources = new Dictionary<SourceKind, SourceSettingsDelta> { [kind] = new(Enabled: enabled) };
            targets.Add(NewTarget(context, new ScopePolicyDelta(Sources: sources)));
        }
        return document with { TargetPolicies = targets };
    }

    /// <summary>
    /// FORCE a source for the target: enable the selected link and every link BELOW
    /// it in the chain, disable every link ABOVE — so the selected one wins when
    /// present (spec §7, no reordering; equivalent to the user clicking that card).
    /// </summary>
    public static MediaPresentationDocument SelectSource(
        MediaPresentationDocument document, ResolutionContext context, SourceKind selected, IReadOnlyList<SourceKind> chainOrder)
    {
        var selectedIndex = Math.Max(0, chainOrder.ToList().IndexOf(selected));
        var targets = document.TargetPolicies.ToList();
        var index = targets.FindIndex(t => SameTarget(t, context));
        var merged = index >= 0 && targets[index].Delta.Sources is { } existing
            ? new Dictionary<SourceKind, SourceSettingsDelta>(existing)
            : new Dictionary<SourceKind, SourceSettingsDelta>();

        for (var i = 0; i < chainOrder.Count; i++)
        {
            var kind = chainOrder[i];
            var source = merged.TryGetValue(kind, out var sd) ? sd : new SourceSettingsDelta();
            merged[kind] = source with { Enabled = i >= selectedIndex };
        }

        if (index >= 0)
            targets[index] = targets[index] with { Delta = targets[index].Delta with { Sources = merged } };
        else
            targets.Add(NewTarget(context, new ScopePolicyDelta(Sources: merged)));
        return document with { TargetPolicies = targets };
    }

    /// <summary>Removes every override for this exact target (reset to the surface).</summary>
    public static MediaPresentationDocument ResetTarget(MediaPresentationDocument document, ResolutionContext context)
        => document with { TargetPolicies = document.TargetPolicies.Where(t => !SameTarget(t, context)).ToList() };

    public static bool HasOverride(MediaPresentationDocument document, ResolutionContext context)
        => document.TargetPolicies.Any(t => SameTarget(t, context));

    private static bool SameTarget(TargetPolicy target, ResolutionContext context)
    {
        if (target.Scope != context.Scope) return false;
        if (!Eq(target.SurfaceId, context.SurfaceId)) return false;
        if (!Eq(target.FrontendSystem, context.FrontendSystem)) return false;
        return context.Scope != MediaScope.Game || Eq(target.GameId, context.StableGameId);
    }

    private static TargetPolicy NewTarget(ResolutionContext context, ScopePolicyDelta delta)
        => new(context.Scope, context.SurfaceId, context.FrontendSystem,
            context.Scope == MediaScope.Game ? context.CanonicalSystem : null,
            context.Scope == MediaScope.Game ? context.StableGameId : null,
            context.Scope == MediaScope.Game ? context.Rom : null,
            delta);

    private static bool Eq(string? a, string? b) => string.Equals(a, b, StringComparison.OrdinalIgnoreCase);
}
